### ISSUE TITLE
variable name is not following the naming convention

### ISSUE THREAD

**Issue by gabrielperales** [daymos/stopWatch#8]
Check [here](https://github.com/daymos/stopWatch/blob/master/js/script.js#L1). Only functions constructors should be named starting by a capital letter. That convention is to know that that function should be called with the `new` operator.

**Comment by daymos** [comment]
ok thanks, will fix it over the weekend.

**Comment by daymos** [comment]
done, have also refactored and separated logic. Let me know if you have any  other comments
